theme: jekyll-theme-minimal
title: Wecome to ffrazatto's homepage!
description: This webpage will be used as my Applied Data Science Capstone Project presentation. I may or may not keep this blog updated afterwards, but this kind of thing is not my cup of tea.
